server:
  port: 9999

#开发配置
spring:
  profiles: dev
  datasource:
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=GMT%2B8
    username: root
    password: ls123
  application:
    name: ProducerUser
  rabbitmq:
    host: 192.168.221.130
    port: 5672
    username: lsadmin
    password: lsadmin
    publisher-confirms: true #消息发到交换机确认机制，是否确认回调
    publisher-returns: true  #消息发到交换机确认机制，是否返回回调
    virtual-host: /ls
---
#默认使用配置
spring:
  profiles:
    active: dev
mybatis:
  mapUnderscoreToCamelCase: true
  typeAliasesPackage: com.ls.pojo
  mapperLocations: classpath:mappers/*.xml
mybatis-plus:
  map-underscore-to-camel-case: true
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.ls.pojo
  configuration:      #配置打印mysql日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com.ls.mapper: debug