server:
  port: 8099

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/redis_demo?serverTimezone=GMT%2B8
    username: root
    password: 123456
    hikari: # https://github.com/brettwooldridge/HikariCP (uses milliseconds for all time values)
      maximumPoolSize: 10
      minimumIdle: 2
      idleTimeout: 600000
      connectionTimeout: 30000
      maxLifetime: 1800000
  # Redis数据库索引（默认为0）
  redis:
    database: 0
     # Redis服务器地址
    host: 192.168.221.136
    # Redis服务器连接端口
    port: 7000
    # Redis服务器连接密码（默认为空）
    password:
    # 连接池最大连接数（使用负值表示没有限制）
    jedis:
      pool:
        max-active: 200
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          #        max-wait: -1
          # 连接池中的最大空闲连接
        max-idle: 10
          # 连接池中的最小空闲连接
        min-idle: 0
      # 连接超时时间（毫秒）
    timeout: 10000

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapUnderscoreToCamelCase: true
  typeAliasesPackage: com.ls.pojo
  mapperLocations: classpath:mappers/*.xml
